# Use pretty URLs (no .html extension)
permalink: pretty

title: Hannah Siegel - Data Science Portfolio

logo: /assets/headshot_b.jpeg
# description: Third-year data science student
# show_download: true
theme: jekyll-theme-minimal


# Navigation links
header_pages:
  - index.md
  - Projects.md
  - Resume.md

baseurl: "/portfolio" # Adjust if your repo is hosted under a subdirectory like 'portfolio'

collections:
  projects:
    output: true
