title: Hannah Siegel

headshot_size: "50px"  # Adjust as needed

logo: /assets/Github_headshot.jpg
# description: Third-year data science student
# show_download: true
theme: jekyll-theme-minimal


# Navigation links
header_pages:
  - index.md
  - Projects.md
  - Resume.md
