title: Hannah Siegel
logo: /assets/Github_headshot.jpg
# description: Third-year data science student
# show_download: true
theme: jekyll-theme-minimal


# Navigation links
header_pages:
  - Homepage.md
  - Projects.md
